os: [ linux ]
dist: xenial
sudo: enabled
language: js

# Install mos tool
addons:
  apt:
    sources:
      - sourceline: "ppa:mongoose-os/mos"
    packages:
      - mos-latest

script:
  - mos version
  - mos build --local --clean --platform esp8266
