steps:
  - script: mos version
    displayName: Mos version
  - script: mos build --clean --platform esp8266
    displayName: Mos Build
  - task: ArchiveFiles@2
    inputs:
      #rootFolderOrFile: '$(Build.BinariesDirectory)\build' 
      #includeRootFolder: true 
      archiveType: 'zip' # Options: zip, 7z, tar, wim
      #tarCompression: 'gz' # Optional. Options: gz, bz2, xz, none
      #archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip' 
      #replaceExistingArchive: true 
      #verbose: # Optional
      #quiet: # Optional
  - task: AzureFileCopy@3
    inputs:
      SourcePath: '$(Build.Repository.LocalPath)'
      ConnectedServiceNameARM: 'Microsoft Azure Sponsorship(69e5dabf-6be7-42fd-bb83-b066e03b4052)'
      Destination: 'AzureBlob'
      StorageAccountRM: 'stodevopsiot001'
      ContainerName: 'devopsiot'
      BlobPrefix: 'fw'